---
- hosts: all
  become: yes
  remote_user: root

  vars_files:
    - vars.yml

  pre_tasks:
    - name: APT ~ Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  handlers:
    - import_tasks: handlers/handlers.yml

  tasks:

    - name: Get software for the apt repo
      apt:
        name: "{{ pkg }}"
        state: present
      vars:
        pkg:
          - ntp
          - python
          - python-apt
          - python-pycurl
          - python-pip
          - git

    - name: Create otto
      user:
        name: otto
        comment: OttO Maker
        groups: adm,sudo

    - name: Create the local ssh directory
      file:
        path: /home/{{ ottouser }}/.ssh
        state: directory
        owner: "{{ ottouser }}"
        group: "{{ ottogroup }}"
        mode: 0700

    - name: Copy private key to host
      copy:
        src: "{{ srcpvtkey }}"
        remote_src: yes
        dest: "{{ dstpvtkey }}"
        owner: "{{ ottouser }}"
        group: "{{ ottogroup }}"
        mode: 0600

    - name: Copy public key to host
      copy:
        remote_src: yes
        src: "{{ srcpubkey }}"
        dest: "{{ dstpubkey }}"
        owner: "{{ ottouser }}"
        group: "{{ ottogroup }}"
        mode: 0644

    - name: Create the local ssh directory
      file:
        path: /srv/stage/
        state: directory
        owner: "{{ ottouser }}"
        group: "{{ ottogroup }}"
        mode: 0755

    - name: Pull this repo on this new
      remote_user: otto
      become: yes
      git:
        repo: git@github.com:mobilerobot-io/"{{ repo }}"
        dest: /srv/stage/"{{ repo }}"
        update: yes
      tags:
        - deploy
      vars:
        repo:
          - clowdops.net
          - otto
          - inventory
