---
- name: Install {{gotar}}
  unarchive:
    src: https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz
    dest: /usr/local
  tags:
    - go

- name: Add to path to otto
  command: echo 'export PATH=$PATH:/usr/local/go/bin' >> /home/otto/.profile
  tags:
    - go
