---
- hosts: all
  remote_user: vagrant
  become_user: root
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: APT ~ Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - common
    - user 

  tasks:
    - name: All Done!
      debug:
        msg: "That's all folks!"

- hosts: otto
  remote_user: root

  vars_files:
    - vars.yml

  roles:
    - otto
    - go

- hosts: nginx
  remote_user: root
  
  vars_files:
    - vars.yml

  roles:
    - nginx
    - sites
