### striaght outta sight
---
- hosts: all
  remote_user: root
  vars_file:
    - vars.yml

  pre_tasks:
    - name: APT ~ update the apt-cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - common
    - user

- hosts: otto
  remote_user: root
  vars_file:
    - vars.yml
  roles:
    - otto
    - go
  
- hosts: nginx
  remote_user: root
  vars_files:
    - vars.yml
  roles:
    - nginx
    - sites

