---
ottouser: otto
ottogroup: otto

srcpubkey: tmp/id_rsa.pub
dstpubkey: /home/otto/.ssh/id_rsa.pub

srcpvtkey: tmp/id_rsa
dstpvtkey: /home/otto/.ssh/id_rsa

# used in our nginx config
wwwport: 80

# GO Variables
godir: /usr/local/go
gohome: /home/otto/go
govers: 1.11.2
goos:   linux
goarch: amd64
gotar: https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz
  
websites:
  - hboilerfootball.org
  - gardenpassages.com
  - sierrahydrographics.com
  - mojavetropicofilming.com
  - skillcraft.com
  
