---
      
- name: Pull the otto repo on this new vm
  git:
    repo: git@github.com:mobilerobot-io/otto
    dest: /srv/src/otto
    update: yes
    accept_hostkey: yes
    key_file: /Users/rusty/.ssh/otto-deploy/id_rsa
  tags:
    - repo
    - otto

- name: Pull down the sites to launch on server
  git:
    repo: git@github.com:mobilerobot-io/clowdops.net
    dest: /srv/src/clowdops.net
    update: yes
    accept_hostkey: yes
    #key_file: "{{ srcpvtkey }}"
  tags:
    - repo
    - clowd

