---
- name: APT ~ update the apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Get software for the apt repo
  remote_user: root
  apt:
    name: "{{ pkg }}"
    state: present
  vars:
    pkg:
      - ntp
      - python
      - python-apt
      - python-pycurl
      - python-pip
      - tcpdump
      - nginx
      - git

