---
- hosts: all
  remote_user: root
  vars_files:
    - vars.yml

  pre_tasks:
    - name: APT ~ Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  handlers:
    - import_tasks: handlers/handlers.yml

  tasks:
    - import_tasks: tasks/common.yml
    - import_tasks: tasks/user.yml
      
    - name: Create the stage directory
      file:
        path: /srv/stage/
        state: directory
        owner: "{{ ottouser }}"
        group: "{{ ottogroup }}"
        mode: 0755

    - name: Add this hosts keys to otto
      authorized_key:
        user: otto
        state: present
        key: "{{ lookup('file', '/Users/rusty/.ssh/id_rsa.pub') }}"
